apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: shang-Eks-Gpu-Cluster
    region: us-east-1

vpc:
    id: "vpc-07ddee12991dcdd2b"
    cidr: "10.7.0.0/17"
    subnets:
      public:
        us-east-1a:
          id: "subnet-0bb0184ea717a920c"
          cidr: "10.7.0.0/20"
        us-east-1b:
          id: "subnet-0274494b3d58357c5"
          cidr: "10.7.16.0/20"
        us-east-1c:
          id: "subnet-0d5f246c0901448f2"
          cidr: "10.7.32.0/20"
        us-east-1d:
          id: "subnet-0fd75bb736cb9015c"
          cidr: "10.7.48.0/20"
        # us-east-1e:
        #   id: "subnet-00e05e1936ab2f0dd"
        #   cidr: "10.7.64.0/20"
        us-east-1f:
          id: "subnet-05c4920f8a3f03a25"
          cidr: "10.7.80.0/20"

nodeGroups:
    - name: gpu-spot
      minSize: 0
      maxSize: 1
      desiredCapacity: 0
      ssh:
        publicKeyPath: ~/.ssh/AwsEc2KeyPair.pub
      instancesDistribution:
        maxPrice: 0.226
        instanceTypes: ["g4dn.2xlarge"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 2
      labels:
        lifecycle: Ec2Spot
        intent: apps
      tags:
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
        k8s.io/cluster-autoscaler/node-template/label/intent: apps
      iam:
        withAddonPolicies:
          autoScaler: false
          cloudWatch: true
          albIngress: true
    - name: cpu-spot-32GB
      minSize: 0
      maxSize: 1
      desiredCapacity: 1
      ssh:
        publicKeyPath: ~/.ssh/AwsEc2KeyPair.pub
      instancesDistribution:
        maxPrice: 0.116
        instanceTypes: ["r5.xlarge"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 2
      labels:
        lifecycle: Ec2Spot
        intent: apps
      tags:
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
        k8s.io/cluster-autoscaler/node-template/label/intent: apps
      iam:
        withAddonPolicies:
          autoScaler: false
          cloudWatch: true
          albIngress: true
    - name: cpu-spot-32GB-disk
      minSize: 0
      maxSize: 1
      desiredCapacity: 0
      volumeSize: 300
      # in GiB
      ssh:
        publicKeyPath: ~/.ssh/AwsEc2KeyPair.pub
      instancesDistribution:
        maxPrice: 0.226
        instanceTypes: ["r5.xlarge"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 2
      labels:
        lifecycle: Ec2Spot
        intent: apps
      tags:
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
        k8s.io/cluster-autoscaler/node-template/label/intent: apps
      iam:
        withAddonPolicies:
          autoScaler: false
          cloudWatch: true
          albIngress: true
    - name: cpu-spot-64GB
      minSize: 0
      maxSize: 1
      desiredCapacity: 0
      ssh:
        publicKeyPath: ~/.ssh/AwsEc2KeyPair.pub
      instancesDistribution:
        maxPrice: 0.226
        instanceTypes: ["r5.2xlarge"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 2
      labels:
        lifecycle: Ec2Spot
        intent: apps
      tags:
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
        k8s.io/cluster-autoscaler/node-template/label/intent: apps
      iam:
        withAddonPolicies:
          autoScaler: false
          cloudWatch: true
          albIngress: true
    - name: cpu-spot-64GB-disk
      minSize: 0
      maxSize: 1
      desiredCapacity: 1
      volumeSize: 300
      ssh:
        publicKeyPath: ~/.ssh/AwsEc2KeyPair.pub
      instancesDistribution:
        maxPrice: 0.326
        instanceTypes: ["r5.2xlarge"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 2
      labels:
        lifecycle: Ec2Spot
        intent: apps
      tags:
        k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
        k8s.io/cluster-autoscaler/node-template/label/intent: apps
      iam:
        withAddonPolicies:
          autoScaler: false
          cloudWatch: true
          albIngress: true

